import fs from "fs";
import path from "path";

import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

import Coach from "../components/Coach";
import { CoachProfile } from "../types/coach";
import Partners from "../components/Partners";

// REVIEW IMPORT FORM JSON COACH
const coachArray = [
  {
    name: "Emy Jamalian",
    img: "/img/coaches/emy.jpg",
    description:
      "is a QA Engineer at Atlas Metrics. Originally from Iran, she moved to Berlin 2,5 years ago. She is a graduate from the web developer bootcamp at Spiced and also studied Information technology engineering in her home country. ",
  },
];

interface Partner {
  logo: string;
  url: string;
}

interface HomeProps {
  files: string[];
  partners: Partner[];
}

export default function Home({ files, partners }: HomeProps) {
  return (
    <>
      <Head>
        <title>Xmas Coding Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          defer
          src="https://code.jquery.com/jquery-3.6.0.min.js"
          integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
          crossOrigin="anonymous"
        ></script>
        <script defer type="text/javascript" src="/script.js"></script>
      </Head>

      <main className={styles.main}>
        <section className={`${styles.animation}`} id="anim-section">
          <Image
            src="/img/home/partners/gdg-google-developer-group-logo.svg"
            className={`${styles.sticky_image}`}
            alt="Vercel Logo"
            width={500}
            height={500}
            objectFit="cover"
          />
        </section>
        <section id="home-section">
          <div className={`${styles.section} ${styles.homeSection}`}></div>
        </section>
        <section
          id="coaches-section"
          className={`${styles.section} ${styles.coachesSection}`}
        >
          {/* Here will be the introduction of the trainees. */}
          <h1 className={styles.titleSection}>Your Coach</h1>
          <div className={styles.coachesProfile}>
            {coachArray &&
              coachArray.map((each: CoachProfile, key) => {
                return <Coach {...each} key={key} />;
              })}
          </div>
        </section>
        <section
          id="material-section"
          className={`${styles.section} ${styles.materialSection}`}
        >
          <h1 className={styles.titleSection}>Material</h1>

          <div className={`${styles.grid} `}>
            <Link href="/material" className={styles.card}>
              <h2>Material &rarr;</h2>
              <p>Find the material form the event here.</p>
            </Link>

            <Link
              href="https://codesandbox.io/s/xmas-coding-2022-qtido4"
              target="_blank"
              className={styles.card}
            >
              <h2>Holiday Card &rarr;</h2>
              <p>
                Here you will find the initial code to do your own holiday card!
              </p>
            </Link>
            {/* <Link
              href="https://xmas-coding-2022.vercel.app "
              target="_blank"
              className={styles.card}
            >
              <h2>Cards Board &rarr;</h2>
              <p>Upload your card and see all the other cards</p>
            </Link> */}

            <Link
              href="https://www.spiced-academy.com/en"
              target="_blank"
              className={styles.card}
            >
              <h2>SPICED Academy &rarr;</h2>
              <p>Take a look at our website and the courses that we offer</p>
            </Link>

            <Link
              href="https://gdg.community.dev/gdg-berlin/"
              target="_blank"
              className={styles.card}
            >
              <h2>GDG Berlin &rarr;</h2>
              <p>
                Take a look at GDG Berlin events and become a member of Google
                Developer Group
              </p>
            </Link>
          </div>
        </section>
        <section
          id="partners-section"
          className={`${styles.section} ${styles.partnerSection}`}
        >
          <h1 className={styles.titleSection}>Our Partners</h1>
          <div className={styles.partnersContainer}>
            {files.map((file: string, key: number) => {
              const partner = partners.find((p) => p.logo === file);
              return partner ? (
                <Partners file={file} url={partner.url} key={key} />
              ) : null;
            })}
          </div>
        </section>
      </main>
    </>
  );
}

export async function getStaticProps() {
  // Get files from the material dir
  let files = fs.readdirSync(path.join("public", "img", "home", "partners"));

  const partners = [
    {
      logo: "gdg-google-developer-group-logo.svg",
      url: "https://gdg.community.dev/gdg-berlin/",
    },
    { logo: "Logo.svg", url: "https://www.neuefische.de/en" },
    { logo: "spiced-logo.svg", url: "https://www.spiced-academy.com/en" },

    // Add more partners
  ];

  files = files.filter((file) => {
    return file.toLocaleLowerCase().includes("logo");
  });

  return { props: { files, partners } };
}
